# Generated by Django 3.2.9 on 2022-11-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Юзернейм')),
                ('name', models.CharField(max_length=100, verbose_name='Название чата')),
                ('link', models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на канал')),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телеграм отправитель id')),
                ('uid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телеграм id')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
