# Generated by Django 3.2.9 on 2022-11-09 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='uid',
        ),
        migrations.AddField(
            model_name='channel',
            name='filter_by_hashtag',
            field=models.BooleanField(default=False, verbose_name='Фильтровать по хэштегу'),
        ),
        migrations.AddField(
            model_name='channel',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None, verbose_name='Хэштеги'),
        ),
    ]
