# Generated by Django 3.2.9 on 2022-11-09 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20221110_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='str через запятую', null=True, size=None, verbose_name='Хэштеги'),
        ),
    ]
