# Generated by Django 3.2.9 on 2022-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221103_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='sender_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телеграм отправитель id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телеграм id'),
        ),
    ]
