# Generated by Django 3.2.9 on 2022-11-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221105_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageentity',
            options={'verbose_name': 'Message Entity', 'verbose_name_plural': 'Message Entities'},
        ),
    ]
