# Generated by Django 3.2.9 on 2022-11-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_channel_name'),
        ('posts', '0007_alter_messageentity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpost',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.channel', verbose_name='Канал'),
        ),
    ]
