# Generated by Django 3.2.9 on 2022-11-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_rawpost_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageentity',
            name='type',
            field=models.CharField(blank=True, choices=[('url', 'URL'), ('text_url', 'Text URL'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('email', 'Email'), ('phone', 'Phone'), ('mention_name', 'Mention Name'), ('mention', 'Mention'), ('hashtag', 'Hashtag')], max_length=20),
        ),
    ]
