# Generated by Django 3.2.9 on 2022-11-09 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_rawpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 21, 38, 26, 128112, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
