# Generated by Django 3.2.9 on 2022-11-09 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_rawpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawpost',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
