# Generated by Django 3.2.9 on 2022-12-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='raw_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.rawpost', verbose_name='Сырой пост'),
        ),
    ]
