# Generated by Django 3.2.9 on 2022-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20221204_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
