# Generated by Django 3.2.9 on 2022-12-10 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст превью'),
        ),
    ]
